version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5437:5432"  # Expose le port 5432 sur le port 5437 de l'hôte
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"  # Expose le port 8085 pour accéder à l'application
    depends_on:
      db:
        condition: service_healthy  # Attendre que la DB soit en bonne santé
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - applogs:/app/logs

volumes:
  pgdata:
  applogs:
